version: '3.9'

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=fretes
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
